name: Laravel Rsync Deploy

on:
  push:
    branches:
      - main

jobs:
  laravel-rsync-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Setup Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install Composer Packages
        run: composer install --no-dev
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '18'
          check-latest: true
      - name: Install NPM dependencies

        run: npm ci

      - name: Compile assets for production

        run: npm run build

      - name: Laravel Rsync Deploy
        uses: SHSharkar/Laravel-Rsync-Deploy@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          ARGS: "--ignore-times --compress --verbose --exclude=.git --exclude=.github --exclude=node_modules --no-perms --no-owner --no-group --recursive"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_HOST_PORT: ${{ secrets.SERVER_PORT }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET_DIRECTORY: ${{ secrets.SERVER_PATH }}
