name: Deploy to production
on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    name: Buid & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Setup Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install Composer Packages
        run: composer install --no-dev
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '18'
          check-latest: true
      - name: Install NPM dependencies

        run: npm ci

      - name: Compile assets for production

        run: npm run build

      - name: Deploy To production
        uses: hypertech-lda/laravel-auto-deploy@1.1
        with:
          user: ${{ secrets.SERVER_USER }}
          host: ${{ secrets.SERVER_HOST }}
          path: ${{ secrets.SERVER_PATH }}
          owner: www
          commands: "# Customer commands"
          # default: php artisan migrate && php artisan cache:clear && php artisan route:cache && php artisan config:cache"
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}


