name: Deploy to production
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Buid & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Setup Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install Composer Packages
        run: composer install --no-dev
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '18'
          check-latest: true
      - name: Install NPM dependencies

        run: npm ci

      - name: Compile assets for production

        run: npm run build

      - name: Deploy To production
        uses: D3rHase/rsync-deploy-action@latest
        with:
          HOST: ${{secrets.HOST}}                             # Remote server address / ip - Required: true
          PORT: ${{secrets.PORT}}                             # Remote server port -  Default: 22 - Required: false
          USER: ${{secrets.USER}}                             # Remote server user - Required: true
          PRIVATE_SSH_KEY: ${{secrets.DEPLOY_KEY}}       # Private ssh key registered on the remote server - Required: true
          SERVER_PATH: ${{secrets.SERVER_PATH}}   


